In [125]:
# import numpy
import numpy as np
# create array x
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [9]:
# print the shape of x
print np.shape(x)


(5,)


In [12]:
# create a two dimensional array
y = np.array([[1,2,3],[3,4,5]])
print y

[[1 2 3]
 [3 4 5]]


In [13]:
# print shape of 2d array
print np.shape(y)

(2, 3)


In [115]:
# reshape the array to 2 x 6
z = np.array([[1,2,3],[3,4,5],[1,2,3],[3,4,5]])
print z
print '\n'
print np.reshape(z,(2,6))


[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


[[1 2 3 3 4 5]
 [1 2 3 3 4 5]]


In [53]:
# reshape the array to 1 x 12
fun = np.reshape(z,(1,12))
print fun

np.transpose(fun)

[[1 2 3 3 4 5 1 2 3 3 4 5]]


array([[1],
       [2],
       [3],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [3],
       [4],
       [5]])

In [180]:
# indexing method 1
#find the 5th value
print fun
print fun[0, 4]

[[1 2 3 3 4 5 1 2 3 3 4 5]]
4


In [179]:
# indexing method 2
# find the 2nd to the last value
print fun
print fun[0, -2]

[[1 2 3 3 4 5 1 2 3 3 4 5]]
4


In [178]:
# indexing method 3
# find the elements 2 to 5 (starting at 0)
print fun
print fun[0, 2:5]


[[1 2 3 3 4 5 1 2 3 3 4 5]]
[3 3 4]


In [177]:
# indexing method 4
# find elements 1,2,3 and 6 (try to index using an array)
index = np.array([1,2,3,6])

print fun
print index
print '\n'
print fun[0, index]



[[1 2 3 3 4 5 1 2 3 3 4 5]]
[1 2 3 6]


[2 3 3 1]


In [169]:
# indexing method 5
# find values in x > 4
print fun
greater_4 = fun > 4
print greater_4
print '\n'
print fun[greater_4]


[[1 2 3 3 4 5 1 2 3 3 4 5]]
[[False False False False False  True False False False False False  True]]


[5 5]


In [189]:
# indexing method 6
# 
y = np.reshape(fun, (3,2,2))
print y
print len(y)
print len(y[0])
print len(y[0][0])
print len(y[1])
print np.shape(y)


[[[1 2]
  [3 3]]

 [[4 5]
  [1 2]]

 [[3 3]
  [4 5]]]
3
2
2
2
(3, 2, 2)
